In [1]:
import pandas as pd

In [ ]:
movies = pd.read_csv('../data/movies.csv/movies.csv')

actors = pd.read_csv('../data/actors.csv/actors.csv')
#only directors
directors = pd.read_csv('../data/crew.csv/crew.csv').query('role == "Director"')
genre = pd.read_csv('../data/genres.csv/genres.csv')
themes = pd.read_csv('../data/themes.csv/themes.csv')

In [ ]:
movies_clean = movies.dropna(subset=['name','description'])
movies_clean['tagline']= movies_clean['tagline'].fillna('')

C:\Users\catas\AppData\Local\Temp\ipykernel_52048\1761586075.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_clean['tagline']= movies_clean['tagline'].fillna('')

id             780783
name           780783
date           713354
tagline        780783
description    780783
minute         697839
rating          90403
dtype: int64

In [ ]:
#join movies with actors
top_actors = actors.groupby('id').head(3)
actors_grouped = top_actors.dropna(subset=['name']).groupby('id')['name'].apply(', '.join).reset_index()
actors_grouped.rename(columns={'name': 'main_actors'}, inplace=True)

        id                                     main_actors
0  1000001    Margot Robbie, Ryan Gosling, America Ferrera
1  1000002       Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong
2  1000003       Michelle Yeoh, Ke Huy Quan, Stephanie Hsu
3  1000004  Edward Norton, Brad Pitt, Helena Bonham Carter
4  1000005           Ryan Gosling, Emma Stone, John Legend

In [ ]:
directors_grouped = directors.dropna(subset=['name']).groupby('id')['name'].apply(', '.join).reset_index()
directors_grouped.rename(columns={'name': 'main_directors'}, inplace=True)

        id                 main_directors
0  1000001                   Greta Gerwig
1  1000002                   Bong Joon-ho
2  1000003  Daniel Scheinert, Daniel Kwan
3  1000004                  David Fincher
4  1000005                Damien Chazelle

In [ ]:
genres_grouped = genre.dropna(subset=['genre']).groupby('id')['genre'].apply(', '.join).reset_index()
genres_grouped.rename(columns={'genre': 'main_genres'}, inplace=True)

        id                                 main_genres
0  1000001                           Comedy, Adventure
1  1000002                     Comedy, Thriller, Drama
2  1000003  Science Fiction, Adventure, Comedy, Action
3  1000004                                       Drama
4  1000005               Drama, Comedy, Music, Romance

In [ ]:
themes_grouped = themes.dropna(subset=['theme']).groupby('id')['theme'].apply(', '.join).reset_index()
themes_grouped.rename(columns={'theme': 'main_themes'}, inplace=True)

        id                                        main_themes
0  1000001  Humanity and the world around us, Crude humor ...
1  1000002  Humanity and the world around us, Intense viol...
2  1000003  Humanity and the world around us, Moving relat...
3  1000004  Intense violence and sexual transgression, Hum...
4  1000005  Song and dance, Humanity and the world around ...

In [25]:
movies_enriched = movies_clean.merge(
    actors_grouped, on='id', how='left') \
    .merge(directors_grouped, on='id', how='left') \
    .merge(genres_grouped, on='id', how='left') \
    .merge(themes_grouped, on='id', how='left')

movies_enriched.head()
movies_enriched.count()

id                780783
name              780783
date              713354
tagline           780783
description       780783
minute            697839
rating             90403
main_actors       538675
main_directors    677012
main_genres       574072
main_themes        24498
dtype: int64

In [26]:
columns_to_fill = ['main_actors', 'main_directors', 'main_genres', 'main_themes']
movies_enriched[columns_to_fill] = movies_enriched[columns_to_fill].fillna('')

In [27]:
movies_enriched.count()

id                780783
name              780783
date              713354
tagline           780783
description       780783
minute            697839
rating             90403
main_actors       780783
main_directors    780783
main_genres       780783
main_themes       780783
dtype: int64

In [29]:
#save enriched data
movies_enriched.to_csv('../data/movies_enriched.csv', index=False)